### ISSUE TITLE
We do not want any magic number in our code 🗡️ 

### ISSUE THREAD

**Issue by incredibleLeitman** [Atia1978/SlotMashineRefactor#1]
https://github.com/Atia1978/SlotMashineRefactor/blob/489c6a28f4968a4f087c73cbaf173dce871d5fe5/SlotMashineRefactor/Program.cs#L9

the initial credit value should 
- either be defined as a constant (you might place that in your Program.cs or create a separate file for your constants)
- or be requested from the user

**Comment by incredibleLeitman** [comment]
Same applies here:
https://github.com/Atia1978/SlotMashineRefactor/blob/489c6a28f4968a4f087c73cbaf173dce871d5fe5/SlotMashineRefactor/SlotMachineLogic.cs#L10C2-L10C61

**Comment by Atia1978** [comment]
I addet option to set initial credit input from user.
