### ISSUE TITLE
Why is 0 not allowed?

### ISSUE THREAD

**Issue by incredibleLeitman** [Atia1978/SlotMashineRefactor#10]
https://github.com/Atia1978/SlotMashineRefactor/blob/489c6a28f4968a4f087c73cbaf173dce871d5fe5/SlotMashineRefactor/SlotMachineLogic.cs#L47-L51

As I understand three matching numbers on a line should grant a win, Independent of which number.
If this is not the case, please specify 
- in the repository read.me file
- in a ui method that welcomes the user and states the rules

This is implemented for rows, cols and jackpot, but not diagonals 🤔

**Comment by Atia1978** [comment]
he logic for checking rows, columns, and diagonals has been improved to ensure three matching numbers on any line trigger a win, regardless of the value.
