### ISSUE TITLE
We don't want any Console.X calls in Logic or Program Main!

### ISSUE THREAD

**Issue by incredibleLeitman** [Atia1978/SlotMashineRefactor#2]
https://github.com/Atia1978/SlotMashineRefactor/blob/489c6a28f4968a4f087c73cbaf173dce871d5fe5/SlotMashineRefactor/Program.cs#L10
https://github.com/Atia1978/SlotMashineRefactor/blob/489c6a28f4968a4f087c73cbaf173dce871d5fe5/SlotMashineRefactor/Program.cs#L33

Those calls should be extracted to your UI class

**Comment by Atia1978** [comment]
i move console output messages to SlotMachineUI class.
