### ISSUE TITLE
Maybe move internal constants to a constants file

### ISSUE THREAD

**Issue by incredibleLeitman** [Atia1978/SlotMashineRefactor#3]
https://github.com/Atia1978/SlotMashineRefactor/blob/489c6a28f4968a4f087c73cbaf173dce871d5fe5/SlotMashineRefactor/SlotMachineUI.cs#L7-L8

For better user experience you maybe also wanna use shorter answers like just "y" or "n" (or even only "y" and any other key means no)

**Comment by Atia1978** [comment]
I refactored  play again prompt to accept shorter inputs ("y" / "n")
