### ISSUE TITLE
Minor: type :D

### ISSUE THREAD

**Issue by incredibleLeitman** [Atia1978/SlotMashineRefactor#4]
https://github.com/Atia1978/SlotMashineRefactor/blob/489c6a28f4968a4f087c73cbaf173dce871d5fe5/SlotMashineRefactor/SlotMachineUI.cs#L30

For all other options you print a whitespace after the number.

To prevent such typos, it is a good way to have a method that prints all enum values using a loop - >this way you have less manual code edits if you decide to extend your enum class

Let us know if you are interested in doing so and we can talk about it in more depth and provide feedback

**Comment by Atia1978** [comment]
i added debugging output to help track winnings calculation.
