### ISSUE TITLE
Hardcoded number!

### ISSUE THREAD

**Issue by incredibleLeitman** [Atia1978/SlotMashineRefactor#5]
https://github.com/Atia1978/SlotMashineRefactor/blob/489c6a28f4968a4f087c73cbaf173dce871d5fe5/SlotMashineRefactor/SlotMachineUI.cs#L42
This can also be dangerous in case you modify your game modes enum -> imagine you add a value and now would allow 1-6 but the error message only shows 1-5
or the other way, you discontinue a mode and the error message would show the user that 1-5 is a valid option where in fact only 1-4 is supported :-o

**Comment by Atia1978** [comment]
i Refactored GameMode display and input validation
