### ISSUE TITLE
Prefer constants over hardcoded numbers

### ISSUE THREAD

**Issue by incredibleLeitman** [Atia1978/SlotMashineRefactor#6]
https://github.com/Atia1978/SlotMashineRefactor/blob/489c6a28f4968a4f087c73cbaf173dce871d5fe5/SlotMashineRefactor/SlotMachineUI.cs#L73

Also, although its exemplary that you thought of error handling here 👍 
think about if this really makes sense 🤔 
What could have happened that Console.ReadLine returns null?

And finally, when providing default fallback values,
you should try to make them as efficient as possible: 
So instead of providing a string "3" that then gets casted to an int anyway 
you could instead just provide an int 3 value :D

**Comment by Atia1978** [comment]
Refactor grid input validation to enforce a minimum value of 3.
