### ISSUE TITLE
Duplicated state tracking

### ISSUE THREAD

**Issue by incredibleLeitman** [Atia1978/SlotMashineRefactor#8]
You have a property that keeps track of money
and functions to support deducting wager and add winnings inside the logic class:
https://github.com/Atia1978/SlotMashineRefactor/blob/489c6a28f4968a4f087c73cbaf173dce871d5fe5/SlotMashineRefactor/SlotMachineLogic.cs#L10-L14

but almost identical code that achieves the same in an separate Player class:
https://github.com/Atia1978/SlotMashineRefactor/blob/489c6a28f4968a4f087c73cbaf173dce871d5fe5/SlotMashineRefactor/Player.cs#L5-L37

This is pretty confusing,
did you really need both of those? Check where and even **if** you are really using those and consolidate

**Comment by Atia1978** [comment]
I refactored the code und deletet from SlotMachineLogic.
