### ISSUE TITLE
Stay consistent in language :D

### ISSUE THREAD

**Issue by incredibleLeitman** [Atia1978/SlotMashineRefactor#9]
https://github.com/Atia1978/SlotMashineRefactor/blob/489c6a28f4968a4f087c73cbaf173dce871d5fe5/SlotMashineRefactor/SlotMachineGewinnElement.cs#L5

"Gewinn" is not an english word so its very uncommon xD

**Comment by Atia1978** [comment]
I changed Gewinn Winnigs .
